### ISSUE TITLE
Remove Debug Banner in Screenshot

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/theta_x_concept_one#1]
In README.md screenshot, considering replacing screenshot with screenshot that does not have the debug banner https://stackoverflow.com/questions/48893935/how-can-i-remove-the-flutter-debug-banner

**Comment by caitlynbakery** [comment]
Ok, I'll do it today

**Comment by jcasman** [comment]
On Line 16 of main.dart, you added `debugShowCheckedModeBanner: false` Is that all it takes?

**Comment by caitlynbakery** [comment]
> On Line 16 of main.dart, you added `debugShowCheckedModeBanner: false` Is that all it takes?

Yes!
