### ISSUE TITLE
format for concept 2

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/theta_x_concept_one#3]
## formatting text output from camera

```dart
var encoder = JsonEncoder.withIndent('   ');
var formattedResponse =
    encoder.convert(jsonDecode(response.body));
```

<img width="331" alt="image" src="https://user-images.githubusercontent.com/5799860/172502043-1947a73f-0398-41e8-a736-675b930b0eca.png">

## scroll with singlechildscrollview

<img width="314" alt="image" src="https://user-images.githubusercontent.com/5799860/172502126-c92c6c7c-a265-4114-ac58-13512e404663.png">

```dart
  Expanded(
      flex: 4, child: SingleChildScrollView(child: Text(message))),
```

**Comment by caitlynbakery** [comment]
Ok, will implement in concept 2
